### ISSUE TITLE
the pretrained Cityscapes model

### ISSUE THREAD

**Issue by JCongLang** [Rorisis/DSRNSS_codes#2]
This is an excellent job！
I encounter a 404 error when downloading the pretrained Cityscapes model.
Could you please provide the pretrained Cityscapes model again?
![image](https://github.com/Rorisis/DSRNSS_codes/assets/108472371/2627c793-c228-4bb3-b1d3-19fbc0d50332)
![image](https://github.com/Rorisis/DSRNSS_codes/assets/108472371/0aeef0e1-0d0d-4e77-9c1c-e61ca7e180ef)

**Comment by Rorisis** [comment]
Could you specify which pretrained model? I found that these pretrained models can be downloaded from [DSRNSS](https://drive.google.com/drive/folders/1g5YQcEd1H-cZ_slpHTWKLk9RtKtUAHBj) and [UAWARP](https://drive.google.com/drive/folders/1E-6shGVlVRn8DlgV5hCTOANdETOmzwsZ)

**Comment by JCongLang** [comment]
> Could you specify which pretrained model? I found that these pretrained models can be downloaded from [DSRNSS](https://drive.google.com/drive/folders/1g5YQcEd1H-cZ_slpHTWKLk9RtKtUAHBj) and [UAWARP](https://drive.google.com/drive/folders/1E-6shGVlVRn8DlgV5hCTOANdETOmzwsZ)

the backbone mit_b5 model pretrained on cityscapes
![image](https://github.com/Rorisis/DSRNSS_codes/assets/108472371/d6cc9feb-e402-4499-90b9-e41d830f7fb1)
Thank you!

**Comment by Rorisis** [comment]
I have uploaded it to [pretrained](https://drive.google.com/drive/folders/1E-6shGVlVRn8DlgV5hCTOANdETOmzwsZ).

**Comment by JCongLang** [comment]
> I have uploaded it to [pretrained](https://drive.google.com/drive/folders/1E-6shGVlVRn8DlgV5hCTOANdETOmzwsZ).

Thank you!
